output_file_path_filtered_data = 'filtered_data.csv'
output_file_path_suicide_df = 'suicide_df.csv'
output_file_path_Natural_disasters_df = 'Natural_disasters_df.csv'
output_file_path_WHR2021_df = 'WHR2021_df.csv'
folder_path = 'data'
folder_path_2 = 'data'