output_file_path_filtered_data = 'export_data/filtered_data.csv'
output_file_path_suicide_df = 'export_data/suicide_df.csv'
output_file_path_Natural_disasters_df = 'export_data/Natural_disasters_df.csv'
output_file_path_WHR2021_df = 'export_data/WHR2021_df.csv'
folder_path = 'data'
folder_path_2 = 'data'